set(CPACK_PACKAGE_NAME "celestron-origin-monitor")
set(CPACK_PACKAGE_VENDOR "CelestronOriginMonitor")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "GUI monitor and controller for Celestron Origin telescopes")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_CONTACT "Celestron Origin Monitor Maintainers")
set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_DEBIAN_PACKAGE_SECTION "science")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Celestron Origin Monitor Maintainers")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
include(CPack)
